<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>OnePlusBuds4</AssemblyName>
    <RootNamespace>OnePlusBuds4</RootNamespace>
    <Title>OnePlus Buds 4 Windows Companion</Title>
    <Product>OnePlus Buds 4 Windows Companion</Product>
    <Description>Windows companion controller for OnePlus Buds 4</Description>
    <Version>1.0.0</Version>
    <Authors>Thomaspatrick14, nic0manz</Authors>
    <RepositoryUrl>https://github.com/Thomaspatrick14/Oneplus-buds4-Win-Companion</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico"/>
    <EmbeddedResource Include="app.ico"/>
  </ItemGroup>

</Project>
